#!/bin/sh

# no kscreen in quantal
quilt pop -a
sed -e '/kubuntu_no_krandr.diff/d' -i patches/series
quilt push -a
# install old randr stuff
sed -e 's/freespacenotifier (>= ${source:Version})/freespacenotifier (>= ${source:Version}), kde-workspace-randr (>= ${source:Version})/' \
    -e 's/kde-base-artwork/kde-base-artwork, kde-workspace-randr/' \
    -i control

cp $hookdir/kdm.upstart.precise kdm.upstart
