#!/bin/sh

cat << EOF >> libgpgme++2.install

usr/lib/libgpgme++-pth.so.2
usr/lib/libgpgme++-pth.so.2.8.0
EOF

cat << EOF >> kdepimlibs5-dev.install

usr/lib/libgpgme++-pth.so
EOF

sed -e '/libaccounts-qt-dev,/d' \
    -i control

sed -e '/libsignon-qt-dev.*)/d' \
    -i control
