#!/usr/bin/python3
# kate: space-indent on; indent-width 4; replace-tabs on; indent-mode python; remove-trailing-space modified;
# vim: expandtab ts=4

############################################################################
#   Copyright © 2015 José Manuel Santamaría Lema <panfaust@gmail.com>      #
#                                                                          #
#   This program is free software; you can redistribute it and/or modify   #
#   it under the terms of the GNU General Public License as published by   #
#   the Free Software Foundation; either version 2 of the License, or      #
#   (at your option) any later version.                                    #
############################################################################

import argparse
import os

from lib.utils import *

#Read configuration files
config_locations = readConfigFile("tarball-locations.json")
config_versions = readConfigFile("versions.json")

#Read arguments finding out the release type (frameworks/plasma/applications)
parser = argparse.ArgumentParser(description="Downloads all the frameworks/plasma/applications tarballs to the"
    " directory configured in 'tarball-locations.json'.")
parser.add_argument("-r", "--releasetype", help="KDE Release Type [frameworks,plasma,applications,kde-l10n]", required=True)
args = parser.parse_args()
release_type = args.releasetype

#Prepare the destination directory
if release_type != "kde-l10n":
    version = config_versions[release_type]
else:
    version = config_versions["applications"]
dest_dir = config_locations[release_type] + "/" + version 
os.makedirs(dest_dir, exist_ok=True)

#Find out the stability
version_parts = version.split(".")
last_digit = int(version_parts[-1])
if last_digit >= 80:
    stability = "unstable"
else:
    stability = "stable"

#Find out which subdirectories we have to inspect in the ftp
ftp_subdirs = []
if release_type == "frameworks":
    ftp_subdirs = ["","portingAids/"]
elif release_type == "plasma":
    ftp_subdirs = [""]
elif release_type == "applications":
    ftp_subdirs = ["src/"]
elif release_type == "kde-l10n":
    release_type = "applications"
    ftp_subdirs = ["src/kde-l10n/"]


url_template = "depot.kde.org:/srv/ftp/pub/kde/%s/%s/%s/%s*.tar.xz"

for subdir in ftp_subdirs:
    url = url_template % (stability,release_type,version,subdir)
    print(url)
    os.system("rsync -avP %s %s" % (url,dest_dir))

