#!/usr/bin/python

import re
import subprocess
import sys

try:
  version = sys.argv[1]
  pimversion = sys.argv[2]
except IndexError:
  print "Usage: kdeapplications-package-names [version] [pimversion]"
  sys.exit(1);

versionParts = version.split(".")
lastDigit = int(versionParts[-1])

if lastDigit >= 80:
    stability = "unstable"
else:
    stability = "stable"

p = subprocess.Popen(["sftp", "-b", "-", "depot.kde.org:/home/ftpubuntu/%s/applications/%s/src/" % (stability, version)], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
output, _ = p.communicate("ls *xz")

for line in output.splitlines():
    match = re.search(r'([a-zA-Z0-9\-]+)-' + re.escape(version) + r'\.tar\.', line)
    if match:
        name = match.group(1)
        if name == "ktux":
            pass
        if name == "libkdegames":
            pass
        else:
            print match.group(1)
    match = re.search(r'([a-zA-Z0-9\-]+)-' + re.escape(pimversion) + r'\.tar\.', line)
    if match:
        name = match.group(1)
        if name == "ktux":
            pass
        else:
            print match.group(1)
print "kde-l10n"
