#!/usr/bin/python

import re
import subprocess
import sys

try:
  version = sys.argv[1]
except IndexError:
  print "Usage: kdeapplications-package-names [version]"
  sys.exit(1);

versionParts = version.split(".")
lastDigit = int(versionParts[-1])

if lastDigit >= 80:
    stability = "unstable"
else:
    stability = "stable"

p = subprocess.Popen(["sftp", "-b", "-", "depot.kde.org:/home/ftpubuntu/%s/applications/%s/src/" % (stability, version)], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
output, _ = p.communicate("ls *xz")

for line in output.splitlines():
    match = re.search(r'([a-zA-Z0-9\-]+)-.*\.tar\.', line)
    if match:
        name = match.group(1)
        if name == "ktux":
            pass
        elif name == "kde-workspace":
            pass
        elif name == "kdelibs":
            print "kde4libs"
        else:
            print match.group(1)
print "kde-l10n"
