#!/usr/bin/python

import re
import subprocess
import sys

try:
  version = sys.argv[1]
except IndexError:
  print "Usage: kf5-package-names [version]"
  sys.exit(1);

versionParts = version.split(".")
lastDigit = int(versionParts[-1])

if lastDigit >= 80:
    stability = "unstable"
else:
    stability = "stable"

p = subprocess.Popen(["sftp", "-b", "-", "depot.kde.org:/home/ftpubuntu/%s/frameworks/%s/" % (stability, version)], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
output, _ = p.communicate("ls *xz")

print "extra-cmake-modules"

for line in output.splitlines():
    match = re.search(r'([a-zA-Z0-9\-]+)-' + re.escape(version) + '\.\d' + r'\.tar\.', line)
    if match:
        name = match.group(1)
        if name == "kwallet":
            print "kwallet-kf5"
        elif name == "kdnssd":
            print "kdnssd-kf5"
        elif name == "kactivities":
            print "kactivities-kf5"
        elif name == "attica":
            print "attica-kf5"
        else:
            print match.group(1)

p = subprocess.Popen(["sftp", "-b", "-", "depot.kde.org:/home/ftpubuntu/%s/frameworks/%s/portingAids/" % (stability, version)], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
output, _ = p.communicate("ls *xz")

for line in output.splitlines():
    match = re.search(r'([a-zA-Z0-9\-]+)-' + re.escape(version) + '\.\d' + r'\.tar\.', line)
    if match:
        name = match.group(1)
        if name == "kwallet":
            print "kwallet-kf5"
        elif name == "kdnssd":
            print "kdnssd-kf5"
        elif name == "kactivities":
            print "kactivities-kf5"
        elif name == "attica":
            print "attica-kf5"
        else:
            print match.group(1)

# kate: space-indent on; indent-width 4; replace-tabs on; indent-mode python; remove-trailing-space on;
