#!/usr/bin/python

import argparse
from distro_info import UbuntuDistroInfo
import glob
from launchpadlib.launchpad import Launchpad
import os
import re
import subprocess
import sys
import tempfile

from lib.utils import *

parser = argparse.ArgumentParser(description="Upload new KDE SC version to the main archive.")
parser.add_argument("-v", "--version", required=True, help="Upstream version")
parser.add_argument("-p", "--packages", help="Override the list packages to upload (comma separated)")
parser.add_argument("-t", "--tmpdir", help="Temporary dir where the packages are prepared")
parser.add_argument("-r", "--releasetype", help="Type [kdeapplications,kdesc,kf5,plasma]", default="kdeapplications")
parser.add_argument("--sru", action="store_true", help="Do a Stable Release Upload")
parser.add_argument("--nopush", action="store_true", help="don't push branches immediately")

args = parser.parse_args()
releaseType = args.releasetype

# git base url for pkg-kde on moszumanska:
debian_git = "git+ssh://git.debian.org/git/pkg-kde/"

version = args.version
if not args.sru:
    release = UbuntuDistroInfo().devel()
else:
    release = UbuntuDistroInfo().stable()

lp = Launchpad.login_anonymously("kubuntu-archive-upload", "production")
ubuntu = lp.distributions["ubuntu"]
lpseries = ubuntu.getSeries(name_or_version=release)
if releaseType == "kf5" or releaseType == "plasma":
#    ppa = lp.people["kubuntu-ninjas"].getPPAByName(name="ppa")
    ppa = lp.people["kubuntu-ppa"].getPPAByName(name="next-staging")
elif not args.sru:
    ppa = lp.people["kubuntu-ninjas"].getPPAByName(name="ppa")
else:
    ppa = lp.people["kubuntu-ppa"].getPPAByName(name="ppa")

if args.packages:
    packages = args.packages.split(",")
else:
    f = open(releaseType + "-packages-" + release + ".txt", "r")
    packages = f.readlines()
    f.close()

    packages = map(lambda line: line.strip("\r\n\t "), packages)
    packages = filter(lambda line: line and not line.startswith("#"), packages)

if args.tmpdir:
    basedir = args.tmpdir
else:
    basedir = tempfile.mkdtemp()
uploaddir = basedir + "/upload"

try:
  os.mkdir(uploaddir)
except OSError:
  print uploaddir + " dir exists"
  pass

skipped = []

topline = re.compile(r'^(\w%(name_chars)s*) \(([^\(\) \t]+)\)'
                     '((\s+%(name_chars)s+)+)\;'
                     % {'name_chars': '[-+0-9a-z.]'},
                     re.IGNORECASE)

def parseChangelogVersions(path):
    f = open(path, "r")
    lines = f.readlines()
    f.close()

    versions = []
    for line in lines:
        match = topline.search(line.strip("\r\n"))
        if match:
            versions.append(match.group(2))
    return versions

for package in packages:
    archive = ubuntu.getArchive(name='primary')
    archive_package = archive.getPublishedSources(source_name=package)
    archive_version = archive_package[0].source_package_version
    if version in archive_version:
        print "=== Skipping %s because version %s is already in the archive" % (package, version)
        continue

    try:
      os.mkdir(basedir + "/" + package)
    except OSError:
      print basedir + "/" + package + " exists"
    os.chdir(basedir + "/" + package)

    if releaseType == "kf5":
#        subprocess.check_call(["pull-ppa-source", "-d", "kubuntu-ninjas/ppa", package, release])
        subprocess.check_call(["pull-ppa-source", "-d", "kubuntu-ppa/next-staging", package, release])
        ninjasDsc = glob.glob("%s_*.dsc" % (package,))[0]

        subprocess.check_call(["git", "clone", debian_git + "frameworks/" + upstreamName(package), "git"])
        os.chdir("git")
        subprocess.check_call(["git", "checkout", "kubuntu_"+release+"_archive"])
    elif releaseType == "plasma":
#        subprocess.check_call(["pull-ppa-source", "-d", "kubuntu-ninjas/ppa", package, release])
        subprocess.check_call(["pull-ppa-source", "-d", "kubuntu-ppa/staging", package, release])
        ninjasDsc = glob.glob("%s_*.dsc" % (package,))[0]

        subprocess.check_call(["git", "clone", debian_git + "plasma/" + upstreamName(package), "git"])
        os.chdir("git")
        subprocess.check_call(["git", "checkout", "kubuntu_"+release+"_archive"])
    elif releaseType == "kdeapplications":
        subprocess.check_call(["pull-ppa-source", "-d", "kubuntu-ninjas/ppa", package, release])
        ninjasDsc = glob.glob("%s_*.dsc" % (package,))[0]

        subprocess.check_call(["git", "clone", debian_git + "kde-applications/" + upstreamName(package), "git"])
        os.chdir("git")
        subprocess.check_call(["git", "checkout", "kubuntu_"+release+"_archive"])
    elif not args.sru:
        subprocess.check_call(["pull-ppa-source", "-d", "kubuntu-ninjas/ppa", package, release])
        ninjasDsc = glob.glob("%s_*.dsc" % (package,))[0]

        subprocess.check_call(["bzr", "branch", "bzr+ssh://bazaar.launchpad.net/~kubuntu-packagers/kubuntu-packaging/" + upstreamName(package), "bzr"])
        os.chdir("bzr")
    else:
        try:
            subprocess.check_call(["pull-ppa-source", "kubuntu-ppa/ppa", package, release])
            ninjasDsc = glob.glob("%s_*.dsc" % (package,))[0]
        except subprocess.CalledProcessError, e:
            if e.returncode == 2:
                print >> sys.stderr, "=== Skipping " + package + ", package not found."
                continue
            else:
                raise e
        try:
            os.chdir(glob.glob("%s-%s*" % (package, version))[0])
        except:
            print "=== Skipping " + package + " because it doesn't match our version"
            continue

    versions = parseChangelogVersions("debian/changelog")
    if version not in versions[0]:
        print >> sys.stderr, "=== Skipping " + package + ", changelog invalid."
        continue
    packageVersion = versions[0]

    changelogRelease = release
    subprocess.check_call(["dch", "-r", "-m", "-D", changelogRelease, ""])

    f = open("debian/changelog", "r")
    changelogLines = f.readlines()
    f.close()

    if "ppa" in changelogLines[0]:
        print >> sys.stderr, "=== Stripping [~ubuntuX]~ppa from version."
        changelogLines[0] = re.sub(r'(~ubuntu[\d\.]+)?~ppa\d+', "", changelogLines[0])
        packageVersion = re.sub(r'(~ubuntu[\d\.]+)?~ppa\d+', "", packageVersion)
        f = open("debian/changelog", "w")
        f.write("".join(changelogLines))
        f.close()
    elif args.sru:
        print >> sys.stderr, "No ~ppa in " + package + "changelog, aborting"
        sys.exit(1)

    if not args.sru:
        if releaseType == "kf5" or releaseType == "plasma" or releaseType == "kdeapplications":
            subprocess.check_call(["git", "commit", "-a", "-m", "NOCI\n Release to " + release + "."])
        else:
            subprocess.check_call(["bzr", "commit", "-m", "Release to " + release + "."])
        try:
            if releaseType == "kf5" or releaseType == "plasma" or releaseType == "kdeapplications":
                #subprocess.check_call(["git-buildpackage", "--git-ignore-branch", "--git-tag-only", "--git-debian-tag='ubuntu/%(version)s'"])
                # don't tag until we know what tags are actually accepted by
                # pkg-kde
                pass
            else:
                subprocess.check_call(["bzr", "tag", packageVersion])
        except:
          print "already tagged"

        if releaseType == "kf5" or releaseType == "plasma" or releaseType == "kdeapplications":
            subprocess.check_call(["git-buildpackage", "--git-ignore-branch", "--git-no-create-orig", "--git-ignore-new", "-S"])
        else:
            subprocess.check_call(["bzr-buildpackage", "-S", "--", "-nc", "-us", "-uc"])
    else:
        subprocess.check_call(["debuild", "-S", "-nc"])

    dscFileVersion = packageVersion
    match = re.search(r'^(\d+:)', dscFileVersion)
    if match:
        dscFileVersion = dscFileVersion[len(match.group(1)):]
    archiveDsc = "%s_%s.dsc" % (package, dscFileVersion)

    os.chdir("..")

    if not args.sru:
        p = subprocess.Popen(["debdiff", ninjasDsc, archiveDsc], stdout=subprocess.PIPE)
        diff, _ = p.communicate()
        if p.returncode != 0 and p.returncode != 1:
            print >> sys.stderr, "=== debdiff error, aborting."
            sys.exit(1)
        p = subprocess.Popen(["diffstat", "-l", "-p1"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
        diffstat, _ = p.communicate(diff)
        diffstatLines = diffstat.strip("\r\n\t ").splitlines()
        ## FIXME: Potential issue for a IndexOutOfRange error
        try:
         if len(diffstatLines) > 1 or diffstatLines[0] != "debian/changelog":
            p = subprocess.Popen(["less"], stdin=subprocess.PIPE)
            p.communicate("Package: %s\n\n=== diffstat ===\n\n%s\n\n=== diff ===\n\n%s" % (package, diffstat, diff))
            sys.stdout.write("==Package %s from the PPA differs from bzr, continue [Y/n]? " % (package))
            choice = raw_input().lower()
            if choice not in ("yes", "y", ""):
                sys.stdout.write("== %s skipped\n" % (package))
                skipped.append(package)
                continue
        except IndexError, e:
          print "IndexOutOfRange" 
        if not args.nopush:
            if releaseType == "kf5" or releaseType == "plasma" or releaseType == "kdeapplications":
                os.chdir("git")
                subprocess.check_call(["git", "push"])
                os.chdir("..")
            else:
                os.chdir("bzr")
                subprocess.check_call(["bzr", "push", ":parent"])
                os.chdir("..")

    subprocess.check_call(["dcmd", "cp", "%s_%s_source.changes" % (package, dscFileVersion), uploaddir])

print "Skipped packages: " + ', '.join(skipped)
# kate: space-indent on; indent-width 4; replace-tabs on; indent-mode python; remove-trailing-space on;
