#!/usr/bin/python

import re
import subprocess
import sys

try:
  version = sys.argv[1]
except IndexError:
  print "Usage: plasma-package-names [version]"
  sys.exit(1);

versionParts = version.split(".")
lastDigit = int(versionParts[-1])

if lastDigit >= 80:
    stability = "unstable"
else:
    stability = "stable"

p = subprocess.Popen(["sftp", "-b", "-", "depot.kde.org:/home/ftpubuntu/%s/plasma/%s/" % (stability, version)], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
output, _ = p.communicate("ls")

for line in output.splitlines():
    match = re.search(r'([a-zA-Z0-9\-]+)-.*\.tar\.', line)
    if match:
        name = match.group(1)
        if name == "baloo":
            print "baloo-kf5"
        elif name == "breeze":
            print "breeze"
            print "breeze-qt4"
        elif name == "oxygen":
            print "oxygen"
            print "oxygen-qt4"
        elif name == "kfilemetadata":
            print "kfilemetadata-kf5"
        else:
            print match.group(1)

            
# kate: space-indent on; indent-width 4; replace-tabs on; indent-mode python; remove-trailing-space on;
