#!/bin/sh

# remove the langpack installation patch, language-selector works in precise
quilt pop -a
sed -e '/kubuntu_langpack_install.diff/d' -i patches/series
quilt push -a
# with this we don't need to depend on qapt and language-selector-common anymore
sed -e 's/, libqapt-dev (>= 1.9.60)//' \
    -e '/^ language-selector-common, libqapt2-runtime$/d' \
    -i control
