#!/bin/sh

# no kscreen in quantal
quilt pop -a
sed -e '/kubuntu_no_krandr.diff/d' -i patches/series
quilt push -a
# install old randr stuff
sed -e 's/freespacenotifier (>= ${source:Version})/freespacenotifier (>= ${source:Version}), kde-workspace-randr (>= ${source:Version})/' \
    -e 's/^ ${sameVersionDep:kdelibs5-dev:kde-workspace-bin}/&, libglapi-mesa-lts-raring, libgl1-mesa-glx-lts-raring, libgles1-mesa-lts-raring/'
    -i control
